package view;

import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import model.Rotas;
import model.Veiculos;

/**
 *
 * @author Mariana Lima
 */
public class DefinirVeiculo extends javax.swing.JPanel {
    private Rotas rota;
    private List<Veiculos> veiculosList;
    private GridBagConstraints gridBagConstraints;
    /**
     * Creates new form DefinirVeiculo
     *
     * @param v
     */
    public DefinirVeiculo(List<Veiculos> v, Rotas rota) {
        veiculosList = v;
        initComponents();
        this.rota = rota;
        gridBagConstraints = new GridBagConstraints();
        
    }

    public void mostraVeiculos(){
        int i=0;
        for (Veiculos ve : veiculosList) {
            JCheckBox btn = new JCheckBox(ve.getNome());
            
            gridBagConstraints.gridx = i;
            gridBagConstraints.gridy = 0;
            i++;
            jPanel1.add(btn, gridBagConstraints);
            btn.addActionListener(new ActionListener() {
                Veiculos vei =ve;
                @Override
                public void actionPerformed(ActionEvent e) {
                    rota.setVeiculo(vei);
                }
            });
            buttonGroup1.add(btn);

        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(422, 300));
        jPanel1.setLayout(new java.awt.GridBagLayout());
        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
