package view;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.AffineTransform;
import java.util.List;
import javax.swing.ImageIcon;
import model.Vertice;
import util.Grafo;

/**
 *
 * @author Mariana Lima
 */


public class Mapa extends javax.swing.JPanel {

    private Grafo grafo;
    private List<Vertice> cidades;
    /**
     * Creates new form Roteiro
     */
    public Mapa() {
        initComponents();
    }

    public Mapa(List<Vertice> cidades) {
        initComponents();
        this.setPreferredSize(new Dimension(720, 1065));
        this.cidades = cidades;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
        /*
	 * Metodo que desenha o grafo na tela.
     */
    @Override
    protected void paintComponent(Graphics graphics) {
        super.paintComponent(graphics);
        Graphics2D graphics2D = (Graphics2D) graphics.create();
        BasicStroke picel1 = new BasicStroke(5, BasicStroke.CAP_SQUARE, BasicStroke.JOIN_BEVEL);
        graphics2D.setColor(Color.RED);
        graphics2D.setStroke(picel1);
        ImageIcon img = new ImageIcon(getClass().getResource("westeros.jpg"));
        graphics2D.drawImage(img.getImage(), 0, 0, this.getWidth(), this.getHeight(), null);
        
        for(Vertice c : cidades){
            System.out.println("x e y: "+ (int)((c.getCoordenadaX()/720)*this.getWidth())+" e "+
                    (int)((c.getCoordenadaY()/2000)*this.getHeight())+" a: "+this.getHeight()+" l: "+this.getWidth());
            graphics2D.fillOval((int)((c.getCoordenadaX()/200)*this.getWidth()), (int)((c.getCoordenadaY()/200)*this.getHeight()), 5, 5);
        }
        
    }
    @Override
    public void repaint(){
        
       
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
