package view;

import controller.RVController;

/**
 *
 * @author Mariana Lima 
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private final RVController controlador;
    
    /**
     * Creates new form TelaPrincipal
     * @param controlador
     */
    public TelaPrincipal(RVController controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        telaInicial = new javax.swing.JDesktopPane();
        cadastroVeiculos = new java.awt.Button();
        definirRoteiro = new java.awt.Button();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Roteamento de Veículos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 312, 107));

        jButton1.setText("Sair");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 60, 30));

        cadastroVeiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cadastroVeiculos.setLabel("Cadastrar Veículos");
        cadastroVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarVeiculosActionPerformed(evt);
            }
        });

        definirRoteiro.setActionCommand("");
        definirRoteiro.setLabel("Definir Roteiro");
        definirRoteiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                definirRoteiroMouseClicked(evt);
            }
        });
        definirRoteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                definirRoteiroActionPerformed(evt);
            }
        });

        telaInicial.setLayer(cadastroVeiculos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaInicial.setLayer(definirRoteiro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaInicialLayout = new javax.swing.GroupLayout(telaInicial);
        telaInicial.setLayout(telaInicialLayout);
        telaInicialLayout.setHorizontalGroup(
            telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaInicialLayout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(definirRoteiro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(265, 265, 265))
        );
        telaInicialLayout.setVerticalGroup(
            telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(cadastroVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(definirRoteiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        cadastroVeiculos.getAccessibleContext().setAccessibleDescription("cadastrar dados dos veículos e preço do combustível");

        getContentPane().add(telaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 520));

        setSize(new java.awt.Dimension(751, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarVeiculosActionPerformed
        // TODO add your handling code here:
        CadastroVeiculos obj = new CadastroVeiculos(controlador);
        telaInicial.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_cadastrarVeiculosActionPerformed

    private void definirRoteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_definirRoteiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_definirRoteiroActionPerformed

    private void definirRoteiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_definirRoteiroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_definirRoteiroMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button cadastroVeiculos;
    private java.awt.Button definirRoteiro;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDesktopPane telaInicial;
    // End of variables declaration//GEN-END:variables
}
